[build]
  command = """
    rustup install nightly --profile minimal \
    && sudo apt-get -y install libpango1.0-dev libgtk-3-dev \
    && cargo doc --no-deps --all-features
    """
  publish = "target/doc"

[build.environment]
  RUSTDOCFLAGS="""
    -D warnings \
    --force-warn rustdoc::redundant-explicit-links \
    --force-warn renamed-and-removed-lints \
    --cfg docsrs
    """
